# Generated by Django 6.0.4 on 2026-05-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_gamificationstate_weekly_mission_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='company_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='company_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
