services:
  backend:
    build: ./backend
    container_name: burnoutzero-backend
    ports:
      - "${DOCKER_BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: burnoutzero-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U burnoutzero" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - "${POSTGRES_DB_PORT}:5432"

volumes:
  postgres_data:
